apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://${PROMETHEUS_IP}:${PROMETHEUS_PORT}
    basicAuth: true
    basicAuthUser: admin
    basicAuthPassword: foobar
    isDefault: true
    editable: true
